INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (1, 'PDF', 8);
INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (2, 'Text documents', 9);
INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (3, 'Spreadsheets', 10);
INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (4, 'Photos & Images', 11);
INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (5, 'Presentations', 12);
INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (6, 'Music', 13);
INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (7, 'Video', 14);
INSERT INTO MEDIA_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (8, 'Others', 15);