INSERT INTO PROCESSES_STATUS(ID_STATUS, TYPE, NAME, FK_ID_TRANSLATION) VALUES(1, 'N', 'Getting certificate', 20);
INSERT INTO PROCESSES_STATUS(ID_STATUS, TYPE, NAME, FK_ID_TRANSLATION) VALUES(2, 'N', 'Certificate', 21);
INSERT INTO PROCESSES_STATUS(ID_STATUS, TYPE, NAME, FK_ID_TRANSLATION) VALUES(1, 'S', 'Pending', 22);
INSERT INTO PROCESSES_STATUS(ID_STATUS, TYPE, NAME, FK_ID_TRANSLATION) VALUES(2, 'S', 'Signed', 23);
INSERT INTO PROCESSES_STATUS(ID_STATUS, TYPE, NAME, FK_ID_TRANSLATION) VALUES(3, 'S', 'Completed', 24);
INSERT INTO PROCESSES_STATUS(ID_STATUS, TYPE, NAME, FK_ID_TRANSLATION) VALUES(4, 'S', 'Canceled', 25);
INSERT INTO PROCESSES_STATUS(ID_STATUS, TYPE, NAME, FK_ID_TRANSLATION) VALUES(5, 'S', 'Expired', 26);