CREATE TABLE ACCOUNT_TYPES
(
  ID_TYPE TINYINT NOT NULL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL,
  FK_ID_TRANSLATION INT NOT NULL,
  COST INT NOT NULL,
  MAX_FILESIZE INT NOT NULL,
  MAX_STORAGE INT NOT NULL,
  MAX_STAMPS_MONTH INT NOT NULL
);