CREATE TABLE BLOCKCHAIN_INFO (
  FK_ID_CLIENT INT NOT NULL PRIMARY KEY,
  ACCOUNT VARCHAR(64) NOT NULL,
  NUMBER_ADDRESSES TINYINT NOT NULL DEFAULT 1,
  TOTAL_UNSPENTS SMALLINT NOT NULL DEFAULT 0,
  AVAILABLE_UNSPENTS SMALLINT NOT NULL DEFAULT 0,
  CTRL_DATE DATETIME,
  CONSTRAINT FK_BLOCKCHAIN_INFO_01 FOREIGN KEY FK_BLOCKCHAIN_INFO_01(FK_ID_CLIENT) REFERENCES OAUTH_CLIENTS(ID_CLIENT) ON DELETE CASCADE
);