CREATE TABLE BULK_TYPES
(
  CLIENT_TYPE ENUM('U','C') NOT NULL,
  FK_ID_CLIENT INT NOT NULL,
  TYPE VARCHAR(32) NOT NULL,
  ELEMENTS_TYPE ENUM ('F','E') NOT NULL,
  BULK_INFO VARCHAR(1000) NOT NULL,
  DEFAULT_INFO VARCHAR(4000),
  PRIMARY KEY (CLIENT_TYPE ASC, FK_ID_CLIENT ASC, TYPE ASC)
);