CREATE TABLE CLIENTS_TYPES
(
  FK_ID_CLIENT INT NOT NULL,
  FK_ID_TYPE TINYINT NOT NULL,
  DATE_START DATETIME NOT NULL,
  NEXT_PAYMENT DATE,
  LAST_RESET DATE,
  DATE_END DATETIME,
  INDEX IX_CLIENTS_TYPES_01 (FK_ID_CLIENT),
  INDEX IX_CLIENTS_TYPES_02(FK_ID_TYPE, NEXT_PAYMENT),
  CONSTRAINT FOREIGN KEY FK_CLIENTS_TYPES_01(FK_ID_TYPE) REFERENCES ACCOUNT_TYPES(ID_TYPE) ON DELETE RESTRICT
);