CREATE TABLE CLIENTS_DELETED (
  ID_CLIENT INT NOT NULL,
  EMAIL VARCHAR(128) NOT NULL,
  PASSWORD VARCHAR(256) NOT NULL,
  TYPE TINYINT NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  SURNAME VARCHAR(256) NULL,
  CONFIRMED TINYINT(1) NOT NULL DEFAULT 0,
  LANG ENUM('en_US','es_ES') NOT NULL,
  CTRL_IP_SIGNUP VARCHAR(128) NOT NULL,
  CTRL_DATE_SIGNUP DATETIME NOT NULL,
  CTRL_IP_MOD VARCHAR(128),
  CTRL_DATE_MOD DATETIME,
  CTRL_IP_LOGIN VARCHAR(128),
  CTRL_DATE_LOGIN DATETIME,
  LAST_ID_GEONAMES INT,
  LAST_LATITUDE DECIMAL(8, 5),
  LAST_LONGITUDE DECIMAL(8, 5)
);