CREATE TABLE EMAILS_TO
(
  FK_ID_USER INT NOT NULL,
  TO_EMAIL VARCHAR(128) NOT NULL,
  FK_ID_EMAIL INT NOT NULL,
INDEX IX_EMAILS_TO_01 (FK_ID_USER ASC, TO_EMAIL ASC),
INDEX IX_EMAILS_TO_02 (FK_ID_EMAIL ASC)
);