CREATE TABLE EMAILS
(
  ID_EMAIL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FK_ID_USER INT NOT NULL,
  CONTENT TEXT NOT NULL,
  SUBJECT VARCHAR(128) NOT NULL,
  ATTACHED_LIST TEXT NOT NULL,
  HASH VARCHAR(64) NOT NULL,
  CTRL_DATE DATETIME NOT NULL,
  CTRL_IP VARCHAR(128) NOT NULL,
  STATUS ENUM('A', 'D') NOT NULL DEFAULT 'A' COMMENT 'A - Active | D - Deleted',
  CTRL_DATE_DEL DATETIME,
  CTRL_IP_DEL VARCHAR(128),
  TRANSACTION VARCHAR(64),
  ID_GEONAMES INT,
  LATITUDE DECIMAL(8, 5),
  LONGITUDE DECIMAL(8, 5),
INDEX IX_EMAILS_01 (FK_ID_USER ASC),
INDEX IX_EMAILS_02 (TRANSACTION ASC),
CONSTRAINT FOREIGN KEY FK_EMAILS_01(TRANSACTION) REFERENCES BLOCKCHAIN(TRANSACTION) ON DELETE RESTRICT
);