CREATE TABLE FILES
(
  ID_FILE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FK_ID_USER INT NOT NULL,
  TYPE ENUM('F', 'E') NOT NULL COMMENT 'F - File | E - Email',
  NAME VARCHAR(128) NOT NULL,
  HASH VARCHAR(64) NOT NULL,
  SIZE INT NOT NULL,
  CTRL_DATE DATETIME NOT NULL,
  CTRL_IP VARCHAR(128) NOT NULL,
  STATUS ENUM('A', 'D') NOT NULL DEFAULT 'A' COMMENT 'A - Active | D - Deleted',
  CTRL_DATE_DEL DATETIME,
  CTRL_IP_DEL VARCHAR(128),
  TRANSACTION VARCHAR(64),
  ID_GEONAMES INT,
  LATITUDE DECIMAL(8, 5),
  LONGITUDE DECIMAL(8, 5),
INDEX IX_FILES_01 (FK_ID_USER ASC),
INDEX IX_FILES_02 (TRANSACTION ASC),
CONSTRAINT FOREIGN KEY FK_FILES_01(TRANSACTION) REFERENCES BLOCKCHAIN(TRANSACTION) ON DELETE RESTRICT
);