CREATE TABLE FILES_SIGNATURE
(
  FK_ID_BULK INT NOT NULL,
  FK_ID_FILE INT NOT NULL,
PRIMARY KEY (FK_ID_BULK, FK_ID_FILE),
INDEX IX_FILES_SIGNATURE_01 (FK_ID_FILE ASC),
CONSTRAINT FK_FILES_SIGNATURE_01 FOREIGN KEY FK_FILES_SIGNATURE_01(FK_ID_BULK) REFERENCES BULK_TRANSACTIONS(ID_BULK_TRANSACTION) ON DELETE CASCADE
);