CREATE TABLE FILES
(
  ID_FILE INT NOT NULL AUTO_INCREMENT,
  FK_ID_USER INT NOT NULL,
  FK_ID_TYPE INT NOT NULL,
  FK_ID_MEDIA INT NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  HASH VARCHAR(64) NOT NULL,
  SIZE INT NOT NULL,
  CTRL_DATE DATETIME NOT NULL,
  CTRL_IP VARCHAR(128) NOT NULL,
  STATUS VARCHAR(1) NOT NULL DEFAULT 'A' COMMENT 'A - Active | T - Trash | D - Deleted',
  CTRL_DATE_DEL DATETIME,
  CTRL_IP_DEL VARCHAR(128),
  TAG VARCHAR(256),
  DESCRIPTION VARCHAR(20000),
  TRANSACTION VARCHAR(64),
  CONFIRMED TINYINT NOT NULL DEFAULT 0 COMMENT '0 - No, 1 - Yes',
  ID_GEONAMES INT,
  LATITUDE DECIMAL(8, 5),
  LONGITUDE DECIMAL(8, 5),
PRIMARY KEY (ID_FILE, STATUS),
INDEX IX_FILES_01 (FK_ID_USER ASC, FK_ID_MEDIA ASC),
UNIQUE INDEX IX_FILES_02 (STATUS ASC, HASH ASC, FK_ID_USER ASC)
)
PARTITION BY LIST COLUMNS(STATUS)
(
  PARTITION ACTIVE_FILES VALUES IN('A'),
  PARTITION DELETED_FILES VALUES IN('T', 'D')
);