CREATE TABLE MEDIA_EXTENSIONS
(
  EXT VARCHAR(10) NOT NULL PRIMARY KEY,
  FK_ID_TYPE INT NOT NULL,
INDEX IX_MEDIA_EXTENSIONS_01 (FK_ID_TYPE ASC),
CONSTRAINT FK_MEDIA_EXTENSIONS_01 FOREIGN KEY FK_MEDIA_EXTENSIONS_01(FK_ID_TYPE) REFERENCES MEDIA_TYPES(ID_TYPE) ON DELETE RESTRICT
);