CREATE TABLE MEDIA_EXTENSIONS
(
  EXT VARCHAR(10) NOT NULL PRIMARY KEY,
  FK_ID_MEDIA INT NOT NULL,
INDEX IX_MEDIA_EXTENSIONS_01 (FK_ID_MEDIA ASC),
CONSTRAINT FOREIGN KEY FK_MEDIA_EXTENSIONS_01(FK_ID_MEDIA) REFERENCES MEDIA_TYPES(ID_MEDIA) ON DELETE RESTRICT
);