CREATE TABLE OAUTH_TOKENS (
  TOKEN VARCHAR(128) NOT NULL PRIMARY KEY,
  TYPE ENUM('A', 'R') NOT NULL COMMENT 'A: Access token, R: Refresh token',
  EXPIRATION DATETIME NOT NULL,
  CTRL_DATE DATETIME NOT NULL,
  CTRL_IP VARCHAR(128) NOT NULL,
  FK_ID_CLIENT INT,
  FK_ID_USER INT,
  FK_ACCESS_TOKEN VARCHAR(128),
  INDEX IX_OAUTH_TOKENS_01 (FK_ACCESS_TOKEN)
);