CREATE TABLE OAUTH_CLIENTS (
  ID_CLIENT INT NOT NULL PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  SECRET VARCHAR(64) NOT NULL,
  ROLE VARCHAR(32) NOT NULL,
  CTRL_DATE DATETIME NOT NULL,
  STATUS ENUM('A', 'I') NOT NULL DEFAULT 'A',
  ALLOWED_IPS VARCHAR(4000),
  STORAGE_LEFT INT,
  STAMPS_LEFT INT,
  UNIQUE INDEX IX_OAUTH_CLIENTS_01 (SECRET)
);