CREATE TABLE PROCESSES_STATUS
(
  ID_STATUS TINYINT NOT NULL,
  TYPE ENUM('N', 'S') NOT NULL COMMENT 'N - Notarization, S - Signature',
  NAME VARCHAR(128) NOT NULL,
  FK_ID_TRANSLATION INT NOT NULL,
PRIMARY KEY (ID_STATUS, TYPE)
);