CREATE TABLE SIGNERS
(
  FK_ID_BULK INT NOT NULL,
  CREATOR TINYINT NOT NULL DEFAULT 0,
  EMAIL VARCHAR(128) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  DOCUMENT VARCHAR(16),
  ACCOUNT VARCHAR(64) NOT NULL,
  TOKEN VARCHAR(64) NOT NULL,
  TOKEN_EXPIRATION DATETIME NOT NULL,
  FK_ID_USER INT,
  FK_ID_IDENTITY INT,
  PHONE VARCHAR(32),
  VIEWED TINYINT NOT NULL DEFAULT 0,
  SIGNED TINYINT NOT NULL DEFAULT 0,
  CTRL_DATE DATETIME,
  CTRL_IP VARCHAR(128),
  ID_GEONAMES INT,
  LATITUDE DECIMAL(8, 5),
  LONGITUDE DECIMAL(8, 5),
PRIMARY KEY (FK_ID_BULK ASC, EMAIL ASC),
UNIQUE INDEX IX_SIGNERS_01 (TOKEN ASC),
FOREIGN KEY FK_SIGNERS_01(FK_ID_BULK) REFERENCES BULK_TRANSACTIONS(ID_BULK_TRANSACTION) ON DELETE RESTRICT
);