CREATE TABLE SIGNERS
(
  ELEMENT_TYPE ENUM('F', 'E') NOT NULL COMMENT 'F - File, E - Email',
  ELEMENT_ID INT NOT NULL,
  CREATOR TINYINT NOT NULL DEFAULT 0,
  EMAIL VARCHAR(128) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  ACCOUNT VARCHAR(64) NOT NULL,
  TOKEN VARCHAR(64) NOT NULL,
  TOKEN_EXPIRATION DATETIME NOT NULL,
  FK_ID_USER INT,
  FK_ID_IDENTITY INT,
  PHONE VARCHAR(12),
  VIEWED TINYINT NOT NULL DEFAULT 0,
  SIGNED TINYINT NOT NULL DEFAULT 0,
  CTRL_DATE DATETIME,
  CTRL_IP VARCHAR(128),
  ID_GEONAMES INT,
  LATITUDE DECIMAL(8, 5),
  LONGITUDE DECIMAL(8, 5),
PRIMARY KEY (ELEMENT_TYPE ASC, ELEMENT_ID ASC, EMAIL ASC),
UNIQUE INDEX IX_SIGNERS_01 (TOKEN ASC)
);