CREATE TABLE SIGN_CODES
(
  TOKEN VARCHAR(64) NOT NULL,
  METHOD ENUM('E', 'P') NOT NULL COMMENT 'E - Email, P - Phone',
  CODE VARCHAR(4) NOT NULL,
  CODE_EXPIRATION DATETIME NOT NULL,
  CTRL_DATE DATETIME NOT NULL,
  CTRL_IP VARCHAR(128),
  ID_GEONAMES INT,
  LATITUDE DECIMAL(8, 5),
  LONGITUDE DECIMAL(8, 5),
INDEX IX_SIG_CODES_01 (TOKEN ASC, CODE ASC)
);