CREATE TABLE SIGNERS
(
  EMAIL VARCHAR(128) NOT NULL PRIMARY KEY,
  FK_ID_USER INT,
  FK_ID_IDENTITY INT,
  PHONE VARCHAR(12),
  CTRL_DATE DATETIME NOT NULL,
  CTRL_IP VARCHAR(128) NOT NULL COMMENT 'Ip address of the origin who added',
INDEX IX_SIGNERS_01 (FK_ID_USER ASC)
);