CREATE TABLE SIGNATURES
(
  ELEMENT_TYPE ENUM('F', 'E') NOT NULL COMMENT 'F - File, E - Email',
  ELEMENT_ID INT NOT NULL,
  EMAIL VARCHAR(128) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  ACCOUNT VARCHAR(64) NOT NULL,
  SIGNED TINYINT NOT NULL DEFAULT 0,
  CTRL_DATE DATETIME,
  CTRL_IP VARCHAR(128),
  ID_GEONAMES INT,
  LATITUDE DECIMAL(8, 5),
  LONGITUDE DECIMAL(8, 5),
PRIMARY KEY (ELEMENT_TYPE ASC, ELEMENT_ID ASC, EMAIL ASC),
INDEX IX_SIGNATURES_01 (EMAIL ASC)
);