DELIMITER //
CREATE TRIGGER TGR_BD_EMAILS
BEFORE DELETE ON EMAILS FOR EACH ROW
BEGIN
  INSERT INTO EMAILS_DELETED
         (ID_EMAIL, FK_ID_USER, CONTENT, SUBJECT, ATTACHED_LIST, HASH, CTRL_DATE, CTRL_IP, CTRL_DATE_DEL, CTRL_IP_DEL,
          TRANSACTION, CONFIRMED, ID_GEONAMES, LATITUDE, LONGITUDE)
  VALUES (OLD.ID_EMAIL, OLD.FK_ID_USER, OLD.CONTENT, OLD.SUBJECT, OLD.ATTACHED_LIST, OLD.HASH, OLD.CTRL_DATE, OLD.CTRL_IP,
          SYSDATE(), OLD.CTRL_IP_DEL, OLD.TRANSACTION, OLD.CONFIRMED, OLD.ID_GEONAMES, OLD.LATITUDE, OLD.LONGITUDE);

  IF OLD.TRANSACTION IS NOT NULL THEN
    UPDATE BLOCKCHAIN SET STATUS_ELEMENT = 'D' WHERE TRANSACTION = OLD.TRANSACTION;
  END IF;

END; //

DELIMITER ;