DELIMITER //
CREATE TRIGGER TGR_BD_FILES
BEFORE DELETE ON FILES FOR EACH ROW
BEGIN
  INSERT INTO FILES_DELETED
         (ID_FILE, FK_ID_USER, FK_ID_TYPE, FK_ID_MEDIA, NAME, FILE_NAME, FILE_ORIG_NAME, HASH, SIZE, CTRL_DATE, CTRL_IP,
          CTRL_DATE_DEL, CTRL_IP_DEL, TAG, DESCRIPTION, TRANSACTION, CONFIRMED, ID_GEONAMES, LATITUDE, LONGITUDE)
  VALUES (OLD.ID_FILE, OLD.FK_ID_USER, OLD.FK_ID_TYPE, OLD.FK_ID_MEDIA, OLD.NAME, OLD.FILE_NAME, OLD.FILE_ORIG_NAME,
          OLD.HASH, OLD.SIZE, OLD.CTRL_DATE, OLD.CTRL_IP, SYSDATE(), OLD.CTRL_IP_DEL, OLD.TAG, OLD.DESCRIPTION,
          OLD.TRANSACTION, OLD.CONFIRMED, OLD.ID_GEONAMES, OLD.LATITUDE, OLD.LONGITUDE);

  IF OLD.TRANSACTION IS NOT NULL THEN
    UPDATE BLOCKCHAIN SET STATUS_ELEMENT = 'D' WHERE TRANSACTION = OLD.TRANSACTION;
  END IF;
END; //

DELIMITER ;