DELIMITER //
CREATE TRIGGER TGR_BD_CLIENTS
BEFORE DELETE ON CLIENTS FOR EACH ROW
BEGIN
  INSERT INTO CLIENTS_DELETED
         (ID_CLIENT, EMAIL, PASSWORD, TYPE, NAME, SURNAME, CONFIRMED, LANG, CTRL_IP_SIGNUP,
          CTRL_DATE_SIGNUP, CTRL_IP_MOD, CTRL_DATE_MOD, CTRL_IP_LOGIN, CTRL_DATE_LOGIN, LAST_ID_GEONAMES,
          LAST_LATITUDE, LAST_LONGITUDE)
  VALUES (OLD.ID_CLIENT, OLD.EMAIL, OLD.PASSWORD, OLD.TYPE, OLD.NAME, OLD.SURNAME, OLD.CONFIRMED, OLD.LANG,
          OLD.CTRL_IP_SIGNUP, OLD.CTRL_DATE_SIGNUP, OLD.CTRL_IP_MOD, OLD.CTRL_DATE_MOD, OLD.CTRL_IP_LOGIN,
          OLD.CTRL_DATE_LOGIN, OLD.LAST_ID_GEONAMES, OLD.LAST_LATITUDE, OLD.LAST_LONGITUDE);
END; //

DELIMITER ;