ALTER TABLE OAUTH_CLIENTS ADD EMAIL VARCHAR(256) AFTER STATUS;
ALTER TABLE OAUTH_CLIENTS ADD (STORAGE_LEFT INT, STAMPS_LEFT INT);

DROP TABLE FILES_DELETED;
DROP TABLE FILES;
DROP TABLE FILE_TYPES;

DELETE FROM TRANSLATIONS WHERE TYPE = 'FT';
ALTER TABLE TRANSLATIONS CHANGE TYPE TYPE ENUM ('AT', 'MT') NOT NULL COMMENT 'AT - ACCOUNT_TYPES, MT - MEDIA_TYPES';
UPDATE TRANSLATIONS SET ID_TRANSLATION = ID_TRANSLATION - 4 WHERE ID_TRANSLATION > 3;

source ../tables/FILES.sql;
source ../tables/FILES_DELETED.sql;
source ../triggers/TGR_BD_FILES.sql;

source ../tables/SIGNERS.sql;
source ../tables/SIGN_CODES.sql;

ALTER TABLE USERS_IDENTITIES ADD DOCUMENT VARCHAR(12) AFTER VALUE;
ALTER TABLE USERS_IDENTITIES ADD ACCOUNT VARCHAR(64) NOT NULL AFTER DOCUMENT;
UPDATE USERS_IDENTITIES SET ACCOUNT = SHA2(CONCAT(NAME, VALUE), 256);

ALTER TABLE USERS ADD PHONE VARCHAR(12) AFTER EMAIL;
ALTER TABLE USERS_DELETED ADD PHONE VARCHAR(12) AFTER EMAIL;
DROP TRIGGER TGR_BD_USERS;
source ../triggers/TGR_BD_USERS.sql;


ALTER TABLE BULK_TYPES ADD ASSET ENUM('N', 'S') NOT NULL COMMENT 'N - Notarization, S - Signature' AFTER TYPE;
ALTER TABLE BULK_TYPES ADD ALLOW_ANONYMOUS TINYINT NOT NULL DEFAULT 0 COMMENT 'Allow anonymous users to insert elements' AFTER ELEMENTS_TYPE;
ALTER TABLE BULK_TYPES CHANGE CLIENT_TYPE CLIENT_TYPE ENUM('U','C', 'A') NOT NULL COMMENT 'U - Logged user, C - Client, A - All users';
UPDATE BULK_TYPES SET ASSET = 'N';
INSERT INTO BULK_TYPES(CLIENT_TYPE, FK_ID_CLIENT, TYPE, ASSET, ELEMENTS_TYPE, ALLOW_ANONYMOUS, BULK_INFO, DEFAULT_INFO, CALLBACK_TYPE, CALLBACK_VALUE)
VALUES ('A', 0, 'Sign Document', 'S', 'E', 1, '{"title":"document","fields":["hash","size","transaction"]}', '{"transaction":"PENDING"}', 'C', 'SignDocument');


ALTER TABLE BULK_TRANSACTIONS ADD ACCOUNT VARCHAR(64) NOT NULL AFTER CTRL_IP_DEL;
ALTER TABLE BULK_TRANSACTIONS ADD LINKED_TRANSACTION VARCHAR(64) AFTER ACCOUNT;
ALTER TABLE BULK_EVENTS CHANGE CLIENT_TYPE CLIENT_TYPE ENUM('U','C');
ALTER TABLE BULK_EVENTS CHANGE FK_ID_CLIENT FK_ID_CLIENT INT;