INSERT INTO ACCOUNT_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION, COST, MAX_FILESIZE, MAX_STORAGE, MAX_STAMPS_MONTH)
VALUES (1, 'Admin', 1, 0, 0, 0, 0);
INSERT INTO ACCOUNT_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION, COST, MAX_FILESIZE, MAX_STORAGE, MAX_STAMPS_MONTH)
VALUES (2, 'Free user', 2, 0, 2048, 524288, 10);
INSERT INTO ACCOUNT_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION, COST, MAX_FILESIZE, MAX_STORAGE, MAX_STAMPS_MONTH)
VALUES (3, 'Premium user', 3, 10, 10240, 52428800, 1000);