INSERT INTO FILE_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (1, 'Document', 4);
INSERT INTO FILE_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (2, 'Bilateral contract', 5);
INSERT INTO FILE_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (3, 'Smart property', 6);
INSERT INTO FILE_TYPES(ID_TYPE, NAME, FK_ID_TRANSLATION) VALUES (4, 'Others', 7);